### ISSUE TITLE
Hello there how to get the date & time?

### ISSUE THREAD

**Issue by veerreef** [mwermuth/MWDatePicker#1]
Hello there how do i nslog the date time in - (void)datePicker:(MWDatePicker*)picker didSelectRow:(NSInteger)row inComponent:(NSInteger)component

**Comment by mwermuth** [comment]
I already implemented a function in MWDatePicker.m called `(NSDate*)getDate;`
But I didn't provide it in the example ;)

I pushed a new commit, so now you will see the NSDate in your Log Window.
